version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
    ports:
      - 5433:5432

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      PATH_TO_UPLOADS: ${PATH_TO_UPLOADS}
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_TEST_PORT: ${DB_TEST_PORT}
      DB_TEST_USER: ${DB_TEST_USER}
      DB_TEST_PASSWORD: ${DB_TEST_PASSWORD}
      DB_TEST_NAME: ${DB_TEST_NAME}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      API_KEY: ${API_KEY}
      JWT_SECRET_RECOVERY_PASSWORD: ${JWT_SECRET_RECOVERY_PASSWORD}
      JWT_SECRET_REFRESH_TOKEN: ${JWT_SECRET_REFRESH_TOKEN}
      JWT_SECRET_ACCESS_TOKEN: ${JWT_SECRET_ACCESS_TOKEN}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      DEFAULT_USER_NAME: ${DEFAULT_USER_NAME}
      DEFAULT_USER_LASTNAME: ${DEFAULT_USER_LASTNAME}
      DEFAULT_USER_EMAIL: ${DEFAULT_USER_EMAIL}
      DEFAULT_USER_USERNAME: ${DEFAULT_USER_USERNAME}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      EMAIL_ADMISSION: ${EMAIL_ADMISSION}
      EMAIL_CHANGE_PASSWORD: ${EMAIL_CHANGE_PASSWORD}
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
  redis_data: