const { User, UserSchema} = require('./user.model');
const { Rol, RolSchema} = require('./rol.model');
const { RolUser, RolUserSchema } = require('./rolUser.model');
const { FilesRegistration, filesRegistrationSchema} = require('./filesRegistration.model');
const { DocumentRegistration, documentRegistrationSchema} = require('./documentRegistration.model');
const { ImageRegistration, imageRegistrationSchema} = require('./imageRegistration.model');
const { ImageNews, imageNewsSchema} = require('./imageNews.model');
const { ImageInstitutionalProjects, imageInstitutionaProjectsSchema } = require('./imageInstitutionalProjects.model');
const { ImageInstitutionalProjectsPublications, imageInstitutionaProjectsPublicationsSchema } = require('./imageInstitutionalProjectPublications.model');
const { ImageUser, imageUserSchema } = require('./imageUser.model');
const { Publications, PublicationsSchema } = require('./publications.model');
const { NewsPublications, NewsPublicationsSchema } = require('./newsPublications.model')
const { InstitutionalProjects, InstitutionalProjectsSchema } = require('./institutionalProjects.model');
const { InstitutionalProjectsPublications, InstitutionalProjectPublicationssSchema } = require('./institutionalProjectsPublications.model');
const { InstitutionalProjectsMember, InstitutionalProjectsMemberSchema } = require('./institucionalProjectMembers.model');
const { InstitutionalProjectsPublicationsAuthors, InstitutionalProjectsPublicationsAuthorsSchema } = require('./institucionalProjectPublicationAuthors.model');
const { ImageBanners, imageBannersSchema } = require('./imageBanners.model');
const { BannersHome, BannersHomeSchema } = require('./bannersHome.model');
const { BannersOurSchool, BannersOurSchoolSchema } = require('./bannersOurSchool.model');
const { BannersInstitutionalProjects, BannersInstitutionalProjectsSchema } = require('./bannersInstitutionalProjects.model');
const { BannersNews, BannersNewsSchema } = require('./bannersNews.model');
const { ImageAcademicLevels, ImageAcademicLevelsSchema } = require('./imageAcademicLevels.model');
const { BannerAcademicLevels, BannersAcademicLevelsSchema } = require('./bannersAcademicLevels.model')
const { BannersAdmissions, BannersAdmissionsSchema } = require('./bannersAdmissions.model');
const { BannersContact, BannersContactSchema } = require('./bannersContact.models');
const { AcademicLevels, AcademicLevelsSchema } = require('./academicLevels.model');
const { AdmissionRequest, admissionRequestSchema} = require('./admissionRequest.model');
const { Calendar, calendarSchema } = require('./calendar.model'); 
const { Clasification, ClasificationSchema } = require('./clasification.model');
const { Categories, CategoriesSchema } = require('./categories.model');
const { Subcategories, subcategoriesSchema } = require('./subcategories.model');
const { Tags, tagsSchema } = require('./tags.model');
const { CategoriesPublications, categoriesPublicationsSchema } = require('./categoriesPublications.model');
const { SubcategoriesPublications, subcategoriesPublicationsSchema} = require('./subcategoriesPublications.model'); 
const { TagsPublications, tagsPublicationsSchema } = require('./tagsPublications.model');
const { CategoriesInstitutionalProjects, categoriesInstitutionalProjectsSchema } = require('./categoriesInstitutionaProjects.model'); 
const { SubcategoriesInstitutionalProjects, subcategoriesInstitutionalProjectsSchema } = require('./subcategoriesInstitutionalProjects.model');
const { TagsInstitutionalProjects, tagsInstitutionalProjectsSchema } = require('./tagsInstitutionalProjects.model');
const { SubjectName, subjectNameSchema } = require('./subjectName.model');
const { Subject, SubjectSchema } = require('./subject.model'); 
const { ScheduleDay, ScheduleDaySchema } = require('./scheduleDay.model');
const { Schedule, SchuduleSchema } = require('./schedule.model'); 
const { SchoolGrade, schoolGradeSchema } = require('./schoolGrade.model');
const { SchoolCourses, schoolCoursesSchema } = require('./schoolCourses.model');

const setupModels = (sequelize) => {
    User.init(UserSchema, User.config(sequelize));
    Rol.init(RolSchema, Rol.config(sequelize));
    RolUser.init(RolUserSchema, RolUser.config(sequelize));
    FilesRegistration.init(filesRegistrationSchema, FilesRegistration.config(sequelize));
    Clasification.init(ClasificationSchema, Clasification.config(sequelize));
    Categories.init(CategoriesSchema, Categories.config(sequelize));
    Subcategories.init(subcategoriesSchema, Subcategories.config(sequelize));
    Tags.init(tagsSchema, Tags.config(sequelize));
    Publications.init(PublicationsSchema, Publications.config(sequelize));
    SchoolGrade.init(schoolGradeSchema, SchoolGrade.config(sequelize));
    SubjectName.init(subjectNameSchema, SubjectName.config(sequelize));
    ImageRegistration.init(imageRegistrationSchema, ImageRegistration.config(sequelize));
    DocumentRegistration.init(documentRegistrationSchema, DocumentRegistration.config(sequelize));
    ImageUser.init(imageUserSchema, ImageUser.config(sequelize));
    CategoriesPublications.init(categoriesPublicationsSchema, CategoriesPublications.config(sequelize));
    SubcategoriesPublications.init(subcategoriesPublicationsSchema, SubcategoriesPublications.config(sequelize));
    TagsPublications.init(tagsPublicationsSchema, TagsPublications.config(sequelize));
    NewsPublications.init(NewsPublicationsSchema, NewsPublications.config(sequelize));
    ImageNews.init(imageNewsSchema, ImageNews.config(sequelize));
    InstitutionalProjects.init(InstitutionalProjectsSchema, InstitutionalProjects.config(sequelize));
    CategoriesInstitutionalProjects.init(categoriesInstitutionalProjectsSchema, CategoriesInstitutionalProjects.config(sequelize)); 
    SubcategoriesInstitutionalProjects.init(subcategoriesInstitutionalProjectsSchema, SubcategoriesInstitutionalProjects.config(sequelize));
    TagsInstitutionalProjects.init(tagsInstitutionalProjectsSchema, TagsInstitutionalProjects.config(sequelize));
    ImageInstitutionalProjects.init(imageInstitutionaProjectsSchema, ImageInstitutionalProjects.config(sequelize));
    InstitutionalProjectsMember.init(InstitutionalProjectsMemberSchema, InstitutionalProjectsMember.config(sequelize));
    InstitutionalProjectsPublications.init(InstitutionalProjectPublicationssSchema, InstitutionalProjectsPublications.config(sequelize));
    InstitutionalProjectsPublicationsAuthors.init(InstitutionalProjectsPublicationsAuthorsSchema, InstitutionalProjectsPublicationsAuthors.config(sequelize));
    ImageInstitutionalProjectsPublications.init(imageInstitutionaProjectsPublicationsSchema, ImageInstitutionalProjectsPublications.config(sequelize));
    ImageBanners.init(imageBannersSchema, ImageBanners.config(sequelize));
    BannersHome.init(BannersHomeSchema, BannersHome.config(sequelize));
    BannersOurSchool.init(BannersOurSchoolSchema, BannersOurSchool.config(sequelize));
    BannersInstitutionalProjects.init(BannersInstitutionalProjectsSchema, BannersInstitutionalProjects.config(sequelize));
    BannersNews.init(BannersNewsSchema, BannersNews.config(sequelize));
    ImageAcademicLevels.init(ImageAcademicLevelsSchema, ImageAcademicLevels.config(sequelize));
    BannersAdmissions.init(BannersAdmissionsSchema, BannersAdmissions.config(sequelize));
    BannerAcademicLevels.init(BannersAcademicLevelsSchema, BannerAcademicLevels.config(sequelize));
    BannersContact.init(BannersContactSchema, BannersContact.config(sequelize));
    AcademicLevels.init(AcademicLevelsSchema, AcademicLevels.config(sequelize));
    AdmissionRequest.init(admissionRequestSchema, AdmissionRequest.config(sequelize));
    Calendar.init(calendarSchema, Calendar.config(sequelize));
    SchoolCourses.init(schoolCoursesSchema, SchoolCourses.config(sequelize));
    Subject.init(SubjectSchema, Subject.config(sequelize));
    ScheduleDay.init(ScheduleDaySchema, ScheduleDay.config(sequelize));
    Schedule.init(SchuduleSchema, Schedule.config(sequelize));

    User.associate(sequelize.models);
    Rol.associate(sequelize.models);
    RolUser.associate(sequelize.models);
    FilesRegistration.associate(sequelize.models);
    DocumentRegistration.associate(sequelize.models);
    ImageRegistration.associate(sequelize.models);
    ImageUser.associate(sequelize.models);
    Clasification.associate(sequelize.models);
    Categories.associate(sequelize.models);
    Subcategories.associate(sequelize.models);
    Tags.associate(sequelize.models);
    CategoriesPublications.associate(sequelize.models);
    SubcategoriesPublications.associate(sequelize.models);
    TagsPublications.associate(sequelize.models);
    Publications.associate(sequelize.models);
    NewsPublications.associate(sequelize.models);
    ImageNews.associate(sequelize.models);
    InstitutionalProjects.associate(sequelize.models);
    InstitutionalProjectsMember.associate(sequelize.models);
    CategoriesInstitutionalProjects.associate(sequelize.models); 
    SubcategoriesInstitutionalProjects.associate(sequelize.models);
    TagsInstitutionalProjects.associate(sequelize.models);
    ImageInstitutionalProjects.associate(sequelize.models);
    InstitutionalProjectsPublications.associate(sequelize.models);
    ImageInstitutionalProjectsPublications.associate(sequelize.models);
    ImageBanners.associate(sequelize.models);
    BannersHome.associate(sequelize.models);
    BannersOurSchool.associate(sequelize.models);
    BannersInstitutionalProjects.associate(sequelize.models);
    BannersNews.associate(sequelize.models);
    ImageAcademicLevels.associate(sequelize.models);
    BannerAcademicLevels.associate(sequelize.models);
    BannersAdmissions.associate(sequelize.models);
    BannersContact.associate(sequelize.models);
    AcademicLevels.associate(sequelize.models);
    SchoolGrade.associate(sequelize.models); 
    AdmissionRequest.associate(sequelize.models);
    SchoolCourses.associate(sequelize.models);
    SubjectName.associate(sequelize.models);
    Subject.associate(sequelize.models);
    ScheduleDay.associate(sequelize.models); 
    Schedule.associate(sequelize.models);
}

module.exports = setupModels;