name: School-api CI
on: [push]

jobs: 
  unit-test: 
    runs-on: ubuntu-latest
    env: 
      PORT: 3001
      NODE_ENV:
      PATH_TO_UPLOADS:
      JWT_SECRET_RECOVERY_PASSWORD:
      JWT_SECRET_REFRESH_TOKEN: 
      JWT_SECRET_ACCESS_TOKEN: 
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 22.3.0
          cache: 'npm'
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash 
        run: npm run test:unit
  integrations-test:
    runs-on: ubuntu-latest

    container:
      image: node:22.3.0

    services:
      postgres-test-integrations: 
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: school_database_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password_test_user

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration
        env: 
          PORT: 3001
          NODE_ENV: test
          PATH_TO_UPLOADS: uploads_test
          JWT_SECRET_RECOVERY_PASSWORD: 
          JWT_SECRET_REFRESH_TOKEN: 
          JWT_SECRET_ACCESS_TOKEN: 
          DB_HOST: localhost
          DB_TEST_PORT: 5433
          DB_TEST_USER: test_user
          DB_TEST_PASSWORD: password_test_user
          DB_TEST_NAME: school_database_test 
